### ISSUE TITLE
Building Tenacity Error

### ISSUE THREAD

**Issue by Barmarel** [tenacityteam/tenacity-legacy#719]
### Guidelines

- [X] I have read the guidelines.

### Describe the bug.

I do everything exactly according to these instructions: https://github.com/tenacityteam/tenacity/blob/master/BUILDING.md

And I get this error when I compile:

`/home/user/tenacity/src/TenacityApp.cpp:872:1: error: 'wxString::wxString(int)' is private within this context
 };
 ^
In file included from /usr/local/include/wx-3.1/wx/bitmap.h:18:0,
                 from /home/user/tenacity/src/TenacityHeaders.h:28,
                 from /home/user/tenacity/build/src/CMakeFiles/Tenacity.dir/cmake_pch.hxx:6,
                 from <command-line>:0:
/usr/local/include/wx-3.1/wx/string.h:324:3: note: declared private here
   wxString(int);
   ^~~~~~~~
[371/750] Building CXX object src/CMakeFiles/Tenacity.dir/AudioIO.cpp.o
ninja: build stopped: subcommand failed.`

How can this be fixed?

### Expected behavior

Compiles without errors.

### OS

Linux Mint 19.3

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by Markon101** [comment]
I have a similar issue in Fedora 36. I get the following. 
`Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  371 | using ValueIterator = std::iterator<
      |                            ^~~~~~~~
In file included from /usr/include/c++/12/bits/stl_algobase.h:65,
                 from /usr/include/c++/12/memory:63,
                 from /home/anon/git/tenacity/src/ProjectFileIO.h:14:
/usr/include/c++/12/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[13/333] Building CXX object src/CMakeFiles/Tenacity.dir/ProjectFileManager.cpp.o
In file included from /home/anon/git/tenacity/src/TenacityException.h:14,
                 from /home/anon/git/tenacity/src/InconsistencyException.h:12,
                 from /home/anon/git/tenacity/src/ClientData.h:21,
                 from /home/anon/git/tenacity/src/ProjectFileManager.h:18,
                 from /home/anon/git/tenacity/src/ProjectFileManager.cpp:11:
/home/anon/git/tenacity/libraries/lib-utility/MemoryX.h:371:28: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  371 | using ValueIterator = std::iterator<
      |                            ^~~~~~~~
In file included from /usr/include/c++/12/bits/stl_construct.h:61,
                 from /usr/include/c++/12/bits/alloc_traits.h:33,
                 from /usr/include/c++/12/ext/alloc_traits.h:34,
                 from /usr/include/c++/12/unordered_map:41,
                 from /usr/include/c++/12/functional:61,
                 from /home/anon/git/tenacity/src/ProjectFileManager.h:14:
/usr/include/c++/12/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
ninja: build stopped: subcommand failed.
`

Latter bit of ninja_log
`4551    7490    1654296157231641236     src/CMakeFiles/Tenacity.dir/ProjectFileManager.cpp.o    1a26a6d325d54c44
6149    7580    1654296157335641781     src/CMakeFiles/Tenacity.dir/ProjectSerializer.cpp.o     1959340bb248cee
6363    7745    1654296157501642651     src/CMakeFiles/Tenacity.dir/ProjectStatus.cpp.o d708aca54d05905b
6230    7867    1654296157623643290     src/CMakeFiles/Tenacity.dir/ProjectSettings.cpp.o       2c52419b2c0e81a0
12      25      0       src/CMakeFiles/version  1c0bddb5839ab800
12      25      0       /home/anon/git/tenacity/build/src/CMakeFiles/version    1c0bddb5839ab800
27      422     1654296268372223656     src/CMakeFiles/Tenacity.dir/RealFFTf48x.cpp.o   14ccdcf62a963ae3
27      699     1654296268648225103     src/CMakeFiles/Tenacity.dir/RealFFTf.cpp.o      5a0ed5a9bc67f92b
28      853     1654296268804225920     src/CMakeFiles/Tenacity.dir/RingBuffer.cpp.o    a6e8c8cf157f4b05
27      1443    1654296269388228981     src/CMakeFiles/Tenacity.dir/Resample.cpp.o      b1bb3a3cffe6a55
27      1815    1654296269749230872     src/CMakeFiles/Tenacity.dir/Registry.cpp.o      701457ed620fa4e8
33      1832    1654296269771230988     src/CMakeFiles/Tenacity.dir/SampleBlock.cpp.o   bcc2b8bf55c8917c
26      1840    1654296269786231066     src/CMakeFiles/Tenacity.dir/ProjectWindowBase.cpp.o     c2b39ec6c768447
423     1870    1654296269818231234     src/CMakeFiles/Tenacity.dir/SampleFormat.cpp.o  7bd6e8ea99f72ebb
26      2357    1654296270292233718     src/CMakeFiles/Tenacity.dir/ProjectWindow.cpp.o 927cff70605599a0
699     2998    1654296270922237019     src/CMakeFiles/Tenacity.dir/Screenshot.cpp.o    6c539a3f90b1aa18
854     3083    1654296271028237575     src/CMakeFiles/Tenacity.dir/SelectUtilities.cpp.o       216789b78be7fd6a
1443    3114    1654296271056237721     src/CMakeFiles/Tenacity.dir/SelectedRegion.cpp.o        c90f6e075d4c9675
1871    3269    1654296271214238549     src/CMakeFiles/Tenacity.dir/ShuttlePrefs.cpp.o  4e9e1c1213d0a99c
1840    3556    1654296271502240059     src/CMakeFiles/Tenacity.dir/Shuttle.cpp.o       bbb7feaad45e6887
1832    3624    1654296271565240389     src/CMakeFiles/Tenacity.dir/Sequence.cpp.o      f1655429a3b09b00
1816    3664    1654296271591240526     src/CMakeFiles/Tenacity.dir/SelectionState.cpp.o        4db58bfa9a62e6fc
3624    3806    1654296271757241395     src/CMakeFiles/Tenacity.dir/SseMathFuncs.cpp.o  39f1a73561f12267
2358    4390    1654296272335244424     src/CMakeFiles/Tenacity.dir/Snap.cpp.o  e6d4f79a8b75efbf
3084    4599    1654296272550245551     src/CMakeFiles/Tenacity.dir/Spectrum.cpp.o      174498b34d285002
2998    4860    1654296272806246892     src/CMakeFiles/Tenacity.dir/SoundActivatedRecord.cpp.o  67ff71263a0adf2c
3114    8654    1654296276589266716     src/CMakeFiles/Tenacity.dir/SpectrumAnalyst.cpp.o       632609096f55bbc6
3806    9406    1654296277344270673     src/CMakeFiles/Tenacity.dir/TempDirectory.cpp.o 8db65b548ed82f36
3269    9836    1654296277771272910     src/CMakeFiles/Tenacity.dir/SplashDialog.cpp.o  13d3636a61c39659
3556    10033   1654296277958273890     src/CMakeFiles/Tenacity.dir/SqliteSampleBlock.cpp.o     81bd176f040d1c1
4601    10071   1654296278014274184     src/CMakeFiles/Tenacity.dir/TimeDialog.cpp.o    9681d55090d991d3
4392    10881   1654296278802278313     src/CMakeFiles/Tenacity.dir/Theme.cpp.o dbd0f43b57168866
4861    11128   1654296279065279691     src/CMakeFiles/Tenacity.dir/TimeTrack.cpp.o     6ad660c6f54137e6
3664    11503   1654296279432281615     src/CMakeFiles/Tenacity.dir/Tags.cpp.o  be9a87e543641672
`
The Flatpak does work well however so that is a temporary workaround for my use case. Thank you all for building a Flatpak image!

**Comment by cbaillou** [comment]
Same issue on the build process :

`cbaillou@cbaillou-dynabook:~/Workspace/PERSO/tenacity$ cmake --build build --config Release`

```
[209/618] Building C object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/xlisp/xlread.c.o
../lib-src/libnyquist/nyquist/xlisp/xlread.c: In function ‘xlload’:
../lib-src/libnyquist/nyquist/xlisp/xlread.c:178:46: warning: ‘%s’ directive output may be truncated writing up to 250 bytes into a region of size 239 [-Wformat-truncation=]
  178 |         { snprintf(buf, STRMAX, "; loading \"%s\"\n", fullname); stdputstr(buf); }
      |                                              ^~       ~~~~~~~~
../lib-src/libnyquist/nyquist/xlisp/xlread.c:178:11: note: ‘snprintf’ output between 14 and 264 bytes into a destination of size 250
  178 |         { snprintf(buf, STRMAX, "; loading \"%s\"\n", fullname); stdputstr(buf); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[216/618] Linking CXX shared library shared/Debug/lib-utility.so
-x /home/cbaillou/Workspace/PERSO/tenacity/build/shared/Debug/lib-utility.so
[220/618] Linking CXX shared library shared/Debug/lib-string-utils.so
-x /home/cbaillou/Workspace/PERSO/tenacity/build/shared/Debug/lib-string-utils.so
[223/618] Building CXX object libraries/lib-strings/CMakeFiles/lib-strings.dir/Languages.cpp.o
../libraries/lib-strings/Languages.cpp: In function ‘void Languages::GetLanguages(FilePaths, wxArrayString&, TranslatableStrings&)’:
../libraries/lib-strings/Languages.cpp:220:26: warning: ‘bool wxFileName::Normalize()’ is deprecated: specify the wanted flags explicitly to avoid surprises [-Wdeprecated-declarations]
  220 |       pathNorm.Normalize();
      |                          ^
In file included from ../libraries/lib-strings/Languages.cpp:43:
/usr/local/include/wx-3.1/wx/filename.h:366:10: note: declared here
  366 |     bool Normalize()
      |          ^~~~~~~~~
[224/618] Linking CXX shared library shared/Debug/lib-strings.so
-x /home/cbaillou/Workspace/PERSO/tenacity/build/shared/Debug/lib-strings.so
[234/618] Building CXX object src/CMakeFiles/Tenacity.dir/TenacityApp.cpp.o
FAILED: src/CMakeFiles/Tenacity.dir/TenacityApp.cpp.o 
/usr/bin/c++  -DCMAKE -DEXPERIMENTAL_DRAGGABLE_PLAY_HEAD -DEXPERIMENTAL_EASY_CHANGE_KEY_BINDINGS -DEXPERIMENTAL_EFFECT_MANAGEMENT -DEXPERIMENTAL_FULL_WASAPI -DEXPERIMENTAL_HALF_WAVE -DEXPERIMENTAL_KEY_VIEW -DEXPERIMENTAL_MODULE_PREFS -DEXPERIMENTAL_NOISE_REDUCTION -DEXPERIMENTAL_NOTETRACK_OVERLAY -DEXPERIMENTAL_NYQUIST_SPLIT_CONTROL -DEXPERIMENTAL_PUNCH_AND_ROLL -DEXPERIMENTAL_REALTIME_AUDACITY_EFFECTS -DEXPERIMENTAL_SCIENCE_FILTERS -DEXPERIMENTAL_SCROLLING_LIMITS -DEXPERIMENTAL_SCRUBBING_SCROLL_WHEEL -DEXPERIMENTAL_SCRUBBING_SUPPORT -DEXPERIMENTAL_SPECTRAL_EDITING -DEXPERIMENTAL_SYNC_LOCK -DEXPERIMENTAL_THEMING -DEXPERIMENTAL_TWO_TONE_TIME_RULER -DEXPERIMENTAL_ZERO_PADDED_SPECTROGRAMS -DEXPERIMENTAL_ZOOM_TOGGLE_BUTTON -DHAVE_IPO -DHAVE_LRINT -DHAVE_LRINTF -DHAVE_MLOCK -DSTRINGS_API="" -DSTRING_UTILS_API="" -DTENACITY_DLL_API="" -DTenacity_EXPORTS -DUTILITY_API="" -DWXUSINGDLL -D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING=1 -D_SILENCE_CXX17_NEGATORS_DEPRECATION_WARNING=1 -D__WXGTK3__ -D__WXGTK__ -Isrc/private -I../include -I../src -I../lib-src/libnyquist/. -I../libraries/lib-string-utils -I../libraries/lib-strings -I../libraries/lib-utility -isystem /usr/local/lib/wx/include/gtk3-unicode-3.1 -isystem /usr/local/include/wx-3.1 -isystem /usr/include/lilv-0 -isystem /usr/include/suil-0 -isystem /usr/include/gtk-3.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/fribidi -isystem /usr/include/harfbuzz -isystem /usr/include/atk-1.0 -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -g   -DAUDACITY_VERSION=3 -DAUDACITY_RELEASE=0 -DAUDACITY_REVISION=2 -DAUDACITY_MODLEVEL=0 -DAUDACITY_VERSION_STRING=L\"Audacity-3.0.2-911-g91f8b43\" -DAUDACITY_FILE_VERSION=L\"3,0,2,0\" -DPROHIBITED==delete -Dsafenew=new -DWXINTL_NO_GETTEXT_MACRO -D_DEBUG=1 -DIS_ALPHA -DUSE_ALPHA_MANUAL -pthread -std=gnu++17 -Winvalid-pch -include /home/cbaillou/Workspace/PERSO/tenacity/build/src/CMakeFiles/Tenacity.dir/cmake_pch.hxx -MD -MT src/CMakeFiles/Tenacity.dir/TenacityApp.cpp.o -MF src/CMakeFiles/Tenacity.dir/TenacityApp.cpp.o.d -o src/CMakeFiles/Tenacity.dir/TenacityApp.cpp.o -c ../src/TenacityApp.cpp
In file included from ../src/TenacityApp.cpp:77:
../src/FFmpeg.h: In member function ‘void AVPacketEx::reset()’:
../src/FFmpeg.h:914:26: warning: ‘void av_free_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  914 |       av_free_packet(this);
      |                          ^
../src/FFmpeg.h:788:7: note: declared here
  788 |       av_free_packet,
      |       ^~~~~~~~~~~~~~
../src/FFmpeg.h:461:19: note: in definition of macro ‘FFMPEG_FUNCTION_NO_RETURN’
  461 |       inline void n a                                                   \
      |                   ^
../src/FFmpeg.h:914:26: warning: ‘void av_free_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  914 |       av_free_packet(this);
      |                          ^
../src/FFmpeg.h:788:7: note: declared here
  788 |       av_free_packet,
      |       ^~~~~~~~~~~~~~
../src/FFmpeg.h:461:19: note: in definition of macro ‘FFMPEG_FUNCTION_NO_RETURN’
  461 |       inline void n a                                                   \
      |                   ^
../src/TenacityApp.cpp: At global scope:
../src/TenacityApp.cpp:872:1: error: ‘wxString::wxString(int)’ is private within this context
  872 | };
      | ^
In file included from /usr/local/include/wx-3.1/wx/bitmap.h:18,
                 from /home/cbaillou/Workspace/PERSO/tenacity/src/TenacityHeaders.h:28,
                 from /home/cbaillou/Workspace/PERSO/tenacity/build/src/CMakeFiles/Tenacity.dir/cmake_pch.hxx:6,
                 from <command-line>:
/usr/local/include/wx-3.1/wx/string.h:324:3: note: declared private here
  324 |   wxString(int);
      |   ^~~~~~~~
[243/618] Building CXX object src/CMakeFiles/Tenacity.dir/BatchProcessDialog.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by FabioLolix** [comment]
Tenacity build with wxWidgets up to v3.1.5, what version are you using?

**Comment by cbaillou** [comment]
I tried first with wxWidgets v3.2 and then v3.1.7
```
$ wx-config --version-full
3.1.7.0
```

**Comment by kogiokka** [comment]
The initializer list at line 871 in `TenacityApp.cpp` causes the issue.  The definition of `wxLanguageInfo` struct has been changed since wxWidgets 3.1.6:
 * 3.1.5: https://docs.wxwidgets.org/3.1.5/structwx_language_info.html
 * 3.1.6: https://docs.wxwidgets.org/3.1.6/structwx_language_info.html

**Comment by cbaillou** [comment]
Building with wxWidgets 3.1.5 solved the problem. Thx @kogiokka
